#ifndef MB_DEVICES_H
#define MB_DEVICES_H

enum MB_Device_Type {
    MB_ALL_DEV = 0x00,
    MB_MASTER_DEV = 0x00,
    MB_NAVLIGHT_DEV = 0x01,
    MB_LIGHT_DEV = 0x02,
    MB_DASHBOARD_DEV = 0x03,
    MB_VSENSE_DEV = 0x04,
    MB_TSENSE_DEV = 0x05,
    MB_PSENSE_DEV = 0x06,
    MB_ISENSE_DEV = 0x07,
    MB_LSENSE_DEV = 0x08,
    MB_DOORSENSE_DEV = 0x09,
    MB_LOCK_DEV = 0x0A,
    MB_KEYPAD_DEV = 0x0B,
    MB_UNKOWN_DEV = 0xFF
};
#endif